### ISSUE TITLE
Scatter's latest version does not have the 12 words recovery interface when downloading a new version

### ISSUE THREAD

**Issue by wutalamanzheng** [nsjames/Scatter#3]
Scatter's latest version does not have the 12-words recovery interface. Unable to find a way to recover the previous set-up scatter account.

**Comment by nsjames** [comment]
This is an extremely defunct repository. You're looking for Scatter's new home at https://github.com/GetScatter/

You can't restore scatter from the 12 word phrase alone. That phrase is only a backup for your password. You need the exported backup to restore an old Scatter, or you can just re-import your private keys.
